version: "3.9"

services:

  api:
    container_name: fastapi_prod
    build:
      context: ..
      dockerfile: docker/Dockerfile.prod
    env_file:
      - ../.env.prod
    volumes:
      - ../logs:/app/logs
    expose:
      - "8000"
    depends_on:
      db:
        condition: service_healthy
    restart: always

  nginx:
    container_name: nginx_prod
    image: nginx:1.25-alpine
    environment:
      - NGINX_DOMAIN=test.prod
      - NGINX_ENVSUBST_TEMPLATE_VARS=NGINX_DOMAIN
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../docker/nginx/templates:/etc/nginx/templates:ro
      - ../docker/nginx/certs:/etc/nginx/certs:ro
      - ../logs/nginx:/var/log/nginx
    depends_on:
      - api

  db:
    container_name: postgres_prod
    image: postgres:15-alpine
    env_file:
      - ../.env.prod
    volumes:
      - postgres_prod:/var/lib/postgresql/data
    expose:
      - "5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always


volumes:
  postgres_prod:
